language: python

python:
  - "2.7"

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=src

install:
  - pip install -U platformio

script:
  - platformio ci --board=pro8MHzatmega328
